<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="5" failures="5" errors="0" time="7.459">
  <testsuite name="POST /human" errors="0" failures="5" skipped="0" timestamp="2024-05-16T16:50:30" time="7.356" tests="5">
    <testcase classname="POST /human should create a new human" name="POST /human should create a new human" time="0.009">
      <failure>MongooseError: Can&apos;t call `openUri()` on an active connection with different connection strings. Make sure you aren&apos;t calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.createClient (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:220:13)
    at NativeConnection.openUri (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\mongoose.js:414:15)
    at C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:11:18
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="GET /human/:id should retrieve a human by id" name="GET /human/:id should retrieve a human by id" time="0.004">
      <failure>MongooseError: Can&apos;t call `openUri()` on an active connection with different connection strings. Make sure you aren&apos;t calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.createClient (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:220:13)
    at NativeConnection.openUri (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\mongoose.js:414:15)
    at C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:11:18
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="PUT /human/:id should update a human by id" name="PUT /human/:id should update a human by id" time="0.008">
      <failure>MongooseError: Can&apos;t call `openUri()` on an active connection with different connection strings. Make sure you aren&apos;t calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.createClient (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:220:13)
    at NativeConnection.openUri (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\mongoose.js:414:15)
    at C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:11:18
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="DELETE /human/:id should delete a human by id" name="DELETE /human/:id should delete a human by id" time="0.005">
      <failure>MongooseError: Can&apos;t call `openUri()` on an active connection with different connection strings. Make sure you aren&apos;t calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.createClient (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:220:13)
    at NativeConnection.openUri (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\mongoose.js:414:15)
    at C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:11:18
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="POST /human should create a new human" name="POST /human should create a new human" time="0.004">
      <failure>MongooseError: Can&apos;t call `openUri()` on an active connection with different connection strings. Make sure you aren&apos;t calling `mongoose.connect()` multiple times. See: https://mongoosejs.com/docs/connections.html#multiple_connections
    at NativeConnection.createClient (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:220:13)
    at NativeConnection.openUri (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\connection.js:801:34)
    at Mongoose.connect (C:\Users\erayz\OneDrive\Desktop\Webframework\node_modules\mongoose\lib\mongoose.js:414:15)
    at C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:11:18
    at Generator.next (&lt;anonymous&gt;)
    at fulfilled (C:\Users\erayz\OneDrive\Desktop\Webframework\tests\Human.test.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." name=" Test execution failure: could be caused by test hooks like &apos;afterAll&apos;." time="0">
      <failure>{&quot;message&quot;:&quot;&quot;,&quot;stack&quot;:&quot;Error: thrown: \&quot;Exceeded timeout of 5000 ms for a hook.\nAdd a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout.\&quot;\n    at Object.&lt;anonymous&gt; (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\testConfig\\setupFile.ts:30:1)\n    at Runtime._execModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1439:24)\n    at Runtime._loadModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:1022:12)\n    at Runtime.requireModule (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runtime\\build\\index.js:882:12)\n    at jestAdapter (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-circus\\build\\legacy-code-todo-rewrite\\jestAdapter.js:70:15)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async runTestInternal (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runner\\build\\runTest.js:367:16)\n    at async runTest (C:\\Users\\erayz\\OneDrive\\Desktop\\Webframework\\node_modules\\jest-runner\\build\\runTest.js:444:34)&quot;}</failure>
    </testcase>
  </testsuite>
</testsuites>